### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by NsrWissam**
tobs-credentails -> tobs-credentials

### CODE REVIEW

**Comment by JamesGuthrie** [comment]
@NsrWissam Thanks for this contribution. There is another occurrence in `./chart/docs/upgrades.md`, could you replace that one too?

**Comment by NsrWissam** [comment]
> @NsrWissam Thanks for this contribution. There is another occurrence in `./chart/docs/upgrades.md`, could you replace that one too?

Done !

**Review by JamesGuthrie — APPROVED** [review]
LGTM

**Comment by NsrWissam** [comment]
Can we retry this build ? it seems there was some timeout unrelated to the changes

**Pull request merged**
